### PR TITLE
Add bindings PGP public key and documentation on how to verify signat…

### PR DESCRIPTION
**Pull request by thunderbiscuit**
This PR adds our public PGP key to the repository, as well as documentation on how to use it to verify signatures on the bdk-jvm and bdk-android artifacts.

### CODE REVIEW

**Comment by notmandatory** [comment]
I think the "Verify Signatures" section can be simplified as below.  Users at a minimum only need to verify the binary artifact signatures match the corresponding .asc file. I don't think they also need to manually check the hashes, this is done with bitcoin core binaries, but it's a more involved process allowing multiple independent people to provide signatures.

# Verify Signatures

Both libraries and all their corresponding artifacts are signed with a PGP key you can find in the 
root of this repository. To verify the signatures follow the below steps:

1. Import the PGP key in your keyring.
   ```shell
    # Navigate to the root of the repository and import the ./PGP-BDK-BINDINGS.asc public key
    gpg --import ./PGP-BDK-BINDINGS.asc
    
    # Alternatively, you can import the key directly from a public key server
    gpg --keyserver keyserver.ubuntu.com --receive-key 2768C43E8803C6A3
    
    # Verify that the correct key was imported
    gpg --list-keys
    
    # You should see the below output
    pub   ed25519 2022-08-31 [SC]
          88AD93AC4589FD090FF3B8D12768C43E8803C6A3
    uid           [ unknown] bitcoindevkit-bindings <bindings@bitcoindevkit.org>
    sub   cv25519 2022-08-31 [E]
   ```
2. Download the binary artifacts and corresponding signature files.
   - from [bdk-jvm]
     - `bdk-jvm-<version>.jar`
     - `bdk-jvm-<version>.jar.asc`  
   - from [bdk-android]  
     - `bdk-android-<version>.aar`
     - `bdk-android-<version>.aar.asc`
3. Verify the signatures.
    ```shell
    gpg --verify bdk-jvm-<version>.jar.asc 
    gpg --verify bdk-android-<version>.aar.asc
   
    # you should see a "Good signature" result
    gpg: Good signature from "bitcoindevkit-bindings <bindings@bitcoindevkit.org>" [unknown]
    ```

**Comment by thunderbiscuit** [comment]
Good ideas. I fixed it all! Ready for re-review.

**Comment by thunderbiscuit** [comment]
This PR fixes #85.

**Review by notmandatory — APPROVED** [review]
ACK 8e7062cc49810349c52a35b8842cb1c59308d81a

Thanks for the updates!

**Pull request merged**
